config/routes.rb
Rails.application.routes.draw do
  resources :pics

  devise_for :admins
  root "pics#index" 

  get "about" =>"pages#about"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :pics
         has_attached_file :cover
         validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
end

app/models/pic.rb
class Pic < ActiveRecord::Base
	belongs_to :admin

	has_attached_file :image, :styles => { :medium => "300x300>", :large => "600x600" }
         validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def create
  @admin = Admin.create( admin_params )
end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def admin_params
  params.require(:admin).permit(:cover)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pics = Pic.all
    respond_with(@pics)
  end

  def show
    respond_with(@pic)
  end

  def new
    @pic = current_admin.pics.build
    respond_with(@pic)
  end

  def edit
  end

  def create
    @pic = current_admin.pics.build(pic_params)
    @pic.save
    respond_with(@pic)
  end

  def update
    @pic.update(pic_params)
    respond_with(@pic)
  end

  def destroy
    @pic.destroy
    respond_with(@pic)
  end

  private
    def set_pic
      @pic = Pic.find(params[:id])
    end

    def pic_params
      params.require(:pic).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/_dropdown.html.erb
<div class="pull-right">
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dLabel" data-toggle="dropdown" aria-expanded="true">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dLabel">
    <% if admin_signed_in? %>
    <li><%= link_to "Admin Logout", destroy_admin_session_path, method: :delete %></li>
    <%else%>
    <li><%= link_to "Admin", admin_session_path %></li>
    <%end%>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another action</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Separated link</a></li>
  </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "JoeJoe's Hair Salon", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
         <% if admin_signed_in? %>
            <li><%= link_to "Admin Settings", edit_admin_registration_path %></li>
            <li><%= link_to 'New Picture', new_pic_path %></li>
            <li><%= link_to "Admin Logout", destroy_admin_session_path, method: :delete %></li>
            <%else%>
            <li><%= link_to "Admin Login", admin_session_path %></li>
            <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joejoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>



</body>
</html>

app/views/pages/_home.html.erb
<div class="wide">

</div>
<div class="container">
  <div class="text-center">
    <h1>Our Models</h1>
  </div>
</div><!-- /.container -->

app/views/pages/about.html.erb
<div class="wide2">

</div>
<div class="container">
  <div class="text-center">
    <h1>About Us</h1>
  </div>
</div><!-- /.container -->

app/views/pics/_form.html.erb
<%= form_for(@pic) do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<%= render 'pages/home'%>
<div id="pics" class = "transitions-enabled">
  <% @pics.each do |pic| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pic.image.url(:medium)), pic_path(pic) %>
      <div class = "panel-body text-center">
      <%= pic.description %>
      <% if pic.admin == current_admin %>
        <%= link_to 'Edit', edit_pic_path(pic) %>
        <%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    </div>
  <% end %>
</div>

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<%= link_to 'Back', pics_path %>


  

        <div class="box2 panel panel-default">
      <%= image_tag @pic.image.url(:large) %>
      <div class = "panel-body text-center">
      <%= @pic.description %>
      <% if @pic.admin == current_admin %>
        <%= link_to 'Edit', edit_pic_path(@pic) %>
        <%= link_to 'Destroy', @pic, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    </div>